name: wiseasy_sdk
description: "Flutter plugin to communicate with Wiseasy devices"
version: 0.0.1
homepage: "https://github.com/visioninvestmentslimited/wiseasy_sdk"

environment:
  sdk: ^3.5.1
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  pigeon: ^22.3.0

flutter:
  plugin:
    platforms:
      android:
        package: com.visionpay.wiseasy_sdk
        pluginClass: WiseasySdkPlugin
